name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'libprotobuf-dev protobuf-compiler libprotoc-dev libzmq3-dev uuid-dev libignition-msgs-dev libignition-tools-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
